version: "3.7"

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    networks:
      - observability-example
    ports:
      - 3010:3000

  prometheus:
    build: ./prometheus
    container_name: prometheus
    restart: unless-stopped
    networks:
      - observability-example
    ports:
      - 9090:9090

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: unless-stopped
    networks:
      - observability-example
    ports:
      - 5672:5672
      - 15672:15672
      - 15692:15692

  seq:
    image: datalust/seq
    container_name: seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    networks:
      - observability-example
    ports:
      - 5341:80

  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    restart: unless-stopped
    networks:
      - observability-example
    ports:
      - 5775:5775/udp
      - 5778:5778
      - 6831:6831/udp
      - 6832:6832/udp
      - 9411:9411
      - 14268:14268
      - 16686:16686

  db-sqlserver:
    container_name: db-sqlserver
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: Ultr@_Secured_P@ssword!123
      ACCEPT_EULA: Y
    networks:
      - observability-example
    ports:
      - 1433:1433

networks:
  observability-example:
    name: observability-example-network